server:
  port: 8080

kaldi:
    model: ${KALDI_SRV_HOME}/data/tri3
    home: /Users/sotheara/Documents/Practice/niptict/asr/kaldi

decode:
    remote: false
    server: localhost
    port: 5010

logging:
  enable: true