server:
  port: 8080

kaldi:
    home: /Users/sotheara/Documents/Practice/niptict/asr/kaldi
    decode:
      remote: false

      model: ${KALDI_SRV_HOME}/data/sgmm2
      sgmm2: true

      server: localhost
      port: 5010

logging:
  enable: false
