server-port: 8080

kaldi-root: /Users/sotheara/Documents/Practice/niptict/asr/kaldi

decode:
  remote: false

  model: ${KALDI_SRV_HOME}/data/tri3
  sgmm2: false

  server: localhost
  port: 5010

logging-enable: false
